[package]
name = "bevy_gltf_model_and_animation_preview"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17.3"
bevy_file_dialog = "0.9"
bevy_panorbit_camera = "0.33"
image = "0.25"
winit = "0.30"
